name: "custom-nodejs

on: push

jobs:
 first-job:
  runs-on: windows-letest
  steps:
   - name: checkout-registry
     runs: action/checkout@v7

   - name: download-nodejs
     usese: action/setup-node@v7
     with:
      node-version:'24'
  
   - name: check-version
     runs: node --version

   - name: run-server
     runs: node server.js
     
