name: multiple-jobs

on: push

jobs:

  my-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Step 1
        run: Write-Output "Starting the server"

      - name: Step 2
        run: node server.js


  second-job:
    runs-on: windows-latest

    steps:
      - name: Step 11
        run: Write-Output "Stopping the server"

      - name: Step 22
        run: Write-Output "exit"
