name: checkout-code

on: push

jobs:
  my-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: server.js

      - name: List repository files
        run: Get-ChildItem
